all:
  hosts:
    master1.k8s.ajway.co.kr:
      ansible_host: 10.10.10.11
      ip: 10.10.10.11
      access_ip: 10.10.10.11
    master2.k8s.ajway.co.kr:
      ansible_host: 10.10.10.12
      ip: 10.10.10.12
      access_ip: 10.10.10.12
    master3.k8s.ajway.co.kr:
      ansible_host: 10.10.10.13
      ip: 10.10.10.13
      access_ip: 10.10.10.13
    worker1.k8s.ajway.co.kr:
      ansible_host: 10.10.10.21
      ip: 10.10.10.21
      access_ip: 10.10.10.21
    worker2.k8s.ajway.co.kr:
      ansible_host: 10.10.10.22
      ip: 10.10.10.22
      access_ip: 10.10.10.22
    worker3.k8s.ajway.co.kr:
      ansible_host: 10.10.10.23
      ip: 10.10.10.23
      access_ip: 10.10.10.23
  children:
    kube-master:
      hosts:
        master1.k8s.ajway.co.kr:
        master2.k8s.ajway.co.kr:
        master3.k8s.ajway.co.kr:
    kube-node:
      hosts:
        worker1.k8s.ajway.co.kr:
        worker2.k8s.ajway.co.kr:
        worker3.k8s.ajway.co.kr:
    etcd:
      hosts:
        master1.k8s.ajway.co.kr:
        master2.k8s.ajway.co.kr:
        master3.k8s.ajway.co.kr:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
